name: CI

on:
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!      
    - name: Print working directory
      run: 
        pwd
    - name: Determine CMake Version
      run:
        cmake --version
    - name: Check gcc version
      run:
        gcc --version
    - name: Prep and Run Tests
      run: |
        mkdir build
        cd build
        cmake ../
        cmake --build .
        ctest 
