name: Master Weekly

on:
  schedule:
    - cron: "0 2 * * 1,6"   

jobs:
  build:
   
    runs-on: windows-2019

    steps:
    - uses: actions/setup-node@master
    - name: Build
      run: |
        mkdir build
        cd build 
        cmake ../
        cmake --build .
    - name: Test
      run: |
        cd build
        ctest -C Debug
        
