name: Master

on:
  push:
    branches: master
  schedule:
    - cron: "0 2 * * 1,6"   

jobs:
  build-windows-2019:
   
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@master
    - name: Build
      run: |
        mkdir build
        cd build 
        cmake ../
        cmake --build .
    - name: Test
      run: |
        cd build
        ctest -C Debug
        

  build-ubuntu-latest:
   
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build
      run: |
        mkdir build
        cd build 
        cmake ../
        make
    - name: Test
      run: |
        cd build
        ctest
        
        
