name: Windows CI

on:
  pull_request:
    branches: 
      - master

jobs:
  build:
   
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        mkdir build
        cd build 
        cmake ../
        cmake --build .
    - name: Test
      run: |
        cd build
        ctest -C Debug
        
