name: Pull Requests

on:
  pull_request:
    branches: 
      - master

jobs:
  build-windows-2019:
   
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        mkdir build
        cd build 
        cmake -G "Ninja" ../
        cmake --build .
    - name: Test
      run: |
        cd build
        ctest -C Debug
        

  build-ubuntu-latest:
   
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        mkdir build
        cd build 
        cmake ../
        make
    - name: Test
      run: |
        cd build
        ctest
        
